name: API Key Setup

on: [push]

jobs:
  setup_api_key:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Print a Message
        run: echo "API key is set up but not displayed here."
        env:
          MY_API_KEY: ${{ secrets.API_KEY }}